# Should minecarts turn into a boat when landing in water?
minecart-transform: true

# Should minecarts that turned into boats drop minecarts?
transformed-drops-minecart: true

# Obsidian boats craftable?
obsidian-boats-exist: true